project:
  type: book
  output-dir: docs

book:
  title: "Pyspark Pieces"
  author: "Abram Astle"
  date: "10/24/2024"
  chapters:
    - index.qmd

    - part: whole-game.qmd
      chapters:
        - set-up.qmd
        - logistic-author.qmd

  page-navigation: true

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

